[okhttp]
title = OkHttp
help = Settings for Android OkHttp extension
group = Android

max_idle_connections.type = integer
max_idle_connections.default = 5
max_idle_connections.label = Max idle connections

keep_alive_duration.type = integer
keep_alive_duration.default = 5
keep_alive_duration.label = Keep alive duration (min)

connect_timeout.type = integer
connect_timeout.default = 10
connect_timeout.label = Connect timeout (sec)

read_timeout.type = integer
read_timeout.default = 10
read_timeout.label = Read timeout (sec)

log.type = integer
log.default = 0
log.options = 0: False, 1: True
